### ISSUE TITLE
Doesnt pull from DB?

### ISSUE THREAD

**Issue by FakeItalianMan** [Dqppp/esx_policemdt#5]
Why is it when I enter an arrest or a Bolo and I go to check it under that category I get an endless loading screen and nothing shows up. Like it is not pulling that information from the database but I cant see what is wrong with it and I get no errors? Any suggestions? Thanks.

**Comment by wood-e** [comment]
I had something very similar which I thought was related to another issue about character lengths. My issue turned out to be that a user had been removed from the database and it was trying to reference that user when loading the MDT menu. Because it never found the user it just showed the loading icon until the resource was restarted.

It might be the same issue. Hopefully, this helps.
